version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./api/docker/Dockerfile
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./api:/go/src/app
  mock-server:
    build:
      context: .
      dockerfile: ./mock-server/docker/Dockerfile
    restart: unless-stopped
    ports:
      - ${MOCK_SERVER_PORT}:3000
    volumes:
      - ./mock-server:/workdir/mock-server
      - ./web:/workdir/web
    tty: true
